### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by wbr1224** [pp9527/LifeGame#1]
- LifeGame-master\LifeGame.py:1:0: C0103: Module name "LifeGame" doesn't conform to snake_case naming style (invalid-name)  模块名“LifeGame”没有遵从 snake_case 命名格式
- LifeGame-master\LifeGame.py:1:0: C0114: Missing module docstring (missing-module-docstring)缺少模块说明
- LifeGame-master\LifeGame.py:23:25: E1101: Module 'pygame' has no 'QUIT' member (no-member)模块‘pygame’没有‘QUIT’成员，或者是‘QUIT’方法
- LifeGame-master\LifeGame.py:24:12: E1101: Module 'pygame' has no 'quit' member (no-member)
同上
- LifeGame-master\LifeGame.py:5:0: C0411: standard import "import sys" should be placed before "import pygame" (wrong-import-order)
错误的导入顺序，sys包应该放在pygame的前面

**Comment by wbr1224** [comment]
Good luck ,gays.Don't forget to give me a star!

**Comment by wbr1224** [comment]
- LifeGame-master\check.py:1:0: C0114: Missing module docstring (missing-module-docstring)
- LifeGame-master\check.py:4:0: C0116: Missing function or method docstring (missing-function-docstring)
缺少模块、方法声明

**Comment by wbr1224** [comment]
init.py:1:0: C0114: Missing module docstring (missing-module-docstring)
init.py:4:0: C0116: Missing function or method docstring (missing-function-docstring)
同上

**Comment by wbr1224** [comment]
- LifeGame-master\newmap.py:1:0: C0114: Missing module docstring (missing-module-docstring)
- LifeGame-master\newmap.py:1:0: C0116: Missing function or method docstring (missing-function-docstring)
- LifeGame-master\newmap.py:5:4: C0200: Consider using enumerate instead of iterating with range and len (consider-using-enumerate)
考虑使用枚举，而不是迭代使用范围和长度
- LifeGame-master\newmap.py:1:0: R0912: Too many branches (13/12) (too-many-branches)
太多的分支

**Comment by wbr1224** [comment]
LifeGame-master\outmap.py:1:0: C0114: Missing module docstring (missing-module-docstring)
LifeGame-master\outmap.py:4:0: C0116: Missing function or method docstring (missing-function-docstring)
LifeGame-master\outmap.py:6:4: E1101: Module 'pygame' has no 'init' member (no-member)
没有‘init’成员
LifeGame-master\outmap.py:10:4: C0200: Consider using enumerate instead of iterating with range and len (consider-using-enumerate)

**Comment by pp9527** [comment]
Thank you for your attention. I will study it carefully and make an update as soon as possible.
